# Generated by Django 5.2.3 on 2025-06-24 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, help_text='nombre de la bebida', null=True, verbose_name='nombre')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de la bebida', max_digits=10, null=True, verbose_name='precio')),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pancho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(help_text='nombre del pancho', verbose_name='nombre')),
                ('precio', models.DecimalField(decimal_places=2, default=0, help_text='precio del pancho expresado en pesos', max_digits=15, verbose_name='precio')),
            ],
            options={
                'verbose_name': 'pancho',
                'verbose_name_plural': 'panchos',
            },
        ),
        migrations.CreateModel(
            name='Salsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('nombreSalsa', models.TextField(blank=True, help_text='nombre de la salsa', null=True, verbose_name='nombreSalsa')),
                ('descripcion', models.TextField(blank=True, help_text='descripcion de la salsa', null=True, verbose_name='descripcion')),
            ],
            options={
                'verbose_name': ('salsa',),
                'verbose_name_plural': 'salsas',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, help_text='nombre de la sucursal', null=True, verbose_name='nombre')),
                ('calle', models.TextField(blank=True, help_text='calle de la sucursal', null=True, verbose_name='calle')),
                ('nroCalle', models.BigIntegerField(blank=True, help_text='nro. de la calle', null=True, verbose_name='nroCalle')),
                ('piso', models.BigIntegerField(blank=True, help_text='nro. de piso', null=True, verbose_name='piso')),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('cantidad', models.BigIntegerField(blank=True, help_text='cantidad panchos', null=True, verbose_name='cantidad')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='subtotal del detalleventa', max_digits=10, null=True, verbose_name='subtotal')),
                ('bebida', models.ForeignKey(blank=True, help_text='bebida encargadas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='panchoneta.bebida')),
                ('pancho', models.ForeignKey(blank=True, help_text='bebida encargadas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='panchoneta.pancho')),
            ],
            options={
                'verbose_name': 'detalleventa',
                'verbose_name_plural': 'detalles',
            },
        ),
        migrations.CreateModel(
            name='DetallePancho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('idPancho', models.ForeignKey(help_text='pancho', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='panchoneta.pancho')),
                ('idSalsa', models.ForeignKey(help_text='salsa', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='panchoneta.salsa')),
            ],
            options={
                'ordering': ['nombre'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo', max_length=200, verbose_name='Nombre')),
                ('fecha', models.DateField(blank=True, help_text='fecha de la venta', null=True, verbose_name='fecha')),
                ('hora', models.TimeField(blank=True, help_text='hora de la venta', null=True, verbose_name='hora')),
                ('sucursal', models.ForeignKey(help_text='sucursal', on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_related', to='panchoneta.sucursal')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
            },
        ),
    ]
