# Generated by Django 5.2.3 on 2025-06-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0002_detalleventa_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salsa',
            name='nombreSalsa',
            field=models.TextField(blank=True, help_text='nombre de la salsa', null=True, verbose_name='nombre'),
        ),
    ]
