# Generated by Django 5.2.3 on 2025-06-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0003_alter_salsa_nombresalsa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salsa',
            name='nombreSalsa',
        ),
        migrations.AlterField(
            model_name='salsa',
            name='nombre',
            field=models.TextField(blank=True, help_text='nombre de la salsa', null=True, verbose_name='nombre'),
        ),
    ]
