# Generated by Django 5.2.3 on 2025-06-24 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0004_remove_salsa_nombresalsa_alter_salsa_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepancho',
            options={},
        ),
        migrations.RemoveField(
            model_name='detallepancho',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='nombre',
        ),
    ]
