# Generated by Django 5.2.3 on 2025-06-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0005_alter_detallepancho_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='subtotal',
        ),
    ]
