# Generated by Django 5.2.3 on 2025-06-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0007_detalleventa_subtotal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'detalleventa', 'verbose_name_plural': 'detallesVenta'},
        ),
    ]
