# Generated by Django 5.2.3 on 2025-06-24 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0009_detalleventa_cantidadbebida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidadBebida',
            field=models.BigIntegerField(blank=True, help_text='cantidad bebidas', null=True, verbose_name='cantidad bebida'),
        ),
    ]
