# Generated by Django 5.2.3 on 2025-06-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0010_alter_detalleventa_cantidadbebida'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='total de la venta', max_digits=12, verbose_name='total'),
        ),
    ]
