# Generated by Django 5.2.3 on 2025-06-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0011_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='total de la venta', max_digits=12, verbose_name='total'),
        ),
    ]
