# Generated by Django 5.2.3 on 2025-06-25 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0012_alter_venta_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='total',
        ),
    ]
