# Generated by Django 5.2.3 on 2025-06-25 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0013_remove_detalleventa_subtotal_remove_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepancho',
            name='idPancho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panchoneta.pancho'),
        ),
        migrations.AlterField(
            model_name='detallepancho',
            name='idSalsa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panchoneta.salsa'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='hora'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panchoneta.sucursal'),
        ),
        migrations.CreateModel(
            name='DetalleBebidaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panchoneta.bebida')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_bebidas', to='panchoneta.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePanchoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('pancho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='panchoneta.pancho')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_panchos', to='panchoneta.venta')),
            ],
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
