# Generated by Django 5.2.3 on 2025-06-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0014_alter_detallepancho_idpancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallebebidaventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detallepanchoventa',
            name='cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
