# Generated by Django 5.2.3 on 2025-06-27 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panchoneta', '0016_alter_bebida_nombre_alter_detallepancho_idpancho_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salsa',
            options={'verbose_name': 'salsa', 'verbose_name_plural': 'salsas'},
        ),
    ]
